# Setup
import neo4j
import random
import json
import requests

from neo4j import GraphDatabase



# Global constant
ICON_PATH = {
    'potential neutral': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/potential.svg',
    'potential danger': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/danger.svg',
    'potential favorable circumstance': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/favorable_circumstance.svg',
    'potentiality neutral': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/potentiality.svg',
    'potentiality risk': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/risk.svg',
    'potentiality opportunity': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/opportunity.svg',
    'actuality neutral': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/actuality.svg',
    'actuality damage': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/damage.svg',
    'actuality benefit': '/r-ioda/webjars/gind/rio/collaborative_model/images/model/nodes/objectives/benefit.svg'
}

EDGE_TYPE = {
    'near': '{http://fr.emac.gind/core-model}Near',
    'generates': '{http://fr.emac.gind/collaborative-model}Generates',
    'proposes': '{http://fr.emac.gind/collaborative-model}Proposes',
    'generated by': '{http://fr.emac.gind/collaborative-model}Generated_By',
    'is susceptible to': '{http://fr.emac.gind/collaborative-model}Is_Susceptible_To',
    'impacts': '{http://fr.emac.gind/collaborative-model}Impacts',
    'reduced impacts': '{http://fr.emac.gind/collaborative-model}Reduced_Impacts',
    'realised': '{http://fr.emac.gind/collaborative-model}Realised',
    'provides': '{http://fr.emac.gind/collaborative-model}Provides',
    'consumes': '{http://fr.emac.gind/collaborative-model}Consumes',
    'requires': '{http://fr.emac.gind/collaborative-model}Requires',
    'produces': '{http://fr.emac.gind/collaborative-model}Produces',
    'satisfies': '{http://fr.emac.gind/collaborative-model}Satisfies',
    'supports': '{http://fr.emac.gind/collaborative-model}Supports',
    'implies': '{http://fr.emac.gind/collaborative-model}Implies',
    'needs': '{http://fr.emac.gind/collaborative-model}Needs',
    'concerns': '{http://fr.emac.gind/collaborative-model}Concerns',
    'acts on': '{http://fr.emac.gind/collaborative-model}Acts_On',
    'fixed onto': '{http://fr.emac.gind/collaborative-model}Fixed_Onto',
    'treated by': '{http://fr.emac.gind/collaborative-model}Treated_By',
    'belongs to': '{http://fr.emac.gind/collaborative-model}Belongs_To',
    'created by': '{http://fr.emac.gind/collaborative-model}Created_By',
    'assigned to': '{http://fr.emac.gind/collaborative-model}Assigned_To',
    'applies on': '{http://fr.emac.gind/collaborative-model}Applies_On',
    'references': '{http://fr.emac.gind/collaborative-model}References',
    'sequence flow': '{http://fr.emac.gind/collaborative-model}Sequence_Flow',
    'has': '{http://fr.emac.gind/system}Has',
    'connected to': '{http://fr.emac.gind/system}Connected_To'
}

HEADERS = {
    "Accept": "application/json",
    "Content-Type": "application/json",
    "User-Agent": "Jersey/3.0.2",
    "Connection": "keep-alive"
}

URL = 'http://172.16.3.244:15001/CEAConnectorService/pushRIOModel'

# Function definition
# Generalize functions
# define a function for initialization
def initialize(uri: str, userName: str, password: str) -> neo4j.Neo4jDriver:
    '''
    uri should be the address of the neo4j server
    userName and password will be used to connect to the neo4j server
    '''
    driver = GraphDatabase.driver(
        uri,
        auth = (userName, password)
    )
    return driver

# define a function to get the name of current knowledge space
def get_current_knowledge_space_name(tx) -> str:
    result = tx.run(
        'MATCH (n:`{http://fr.emac.gind/iosuite/project}Project`)'
        'RETURN n.property_name'
    )
    for record in result:
        return record.value().replace(' ', '_')

# define a function to get the name of current collaboration
def get_current_collaboration_name(tx) -> str:
    currentCollaborationName = get_property_node(tx, 1, 'property_name').replace(' ', '_')
    #return 'R-IO_Suite_WorkSpace'
    return currentCollaborationName

# define a function to generate ID for view randomly
def generate_view_id() -> str:
    id1 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 8))
    id2 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id3 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id4 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id5 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 12))
    viewId = 'view_' + id1 + '-' + id2 + '-' + id3 + '-' + id4 + '-' + id5
    return viewId

# define a function to replace '[]' with an empty list in dict
def replace_list(dic):
    for key in dic.keys():
        if type(dic[key]) is dict:
            replace_list(dic[key])
        else:
            if dic[key] == '[]':
                dic[key] = []

# define a function to reformalize the property
def reformalize_property(propertyValue: str):
    if len(propertyValue) != 0:
        if (propertyValue[0] == '[' and propertyValue[-1] == ']') or (propertyValue[0] == '{' and propertyValue[-1] == '}'):
            start = propertyValue.find('<')
            end = propertyValue[::-1].find('>')
            if start == -1 and end == -1:
                try:
                    return json.loads(propertyValue.replace('\'\'\'', '\'').replace('\'', '\"').replace('\"[', '[').replace(']\"', ']'))
                except:
                    return propertyValue[1:-1].split(', ')
            else:
                try:
                    return json.loads(propertyValue[:start].replace('\'', '\"') + propertyValue[start:-end] + propertyValue[-end:].replace('\'', '\"'))
                except:
                    return 'XML Decoding Failed !'
        else:
            try:
                return float(propertyValue)
            except:
                return propertyValue
    else:
        return propertyValue

# Functions for node
# define a function to get all nodes' names
def get_all_nodes_names(tx) -> list:
    names = []
    result = tx.run(
        "MATCH (n) RETURN n.property_name"
    )
    for record in result:
        if not record.value() in names:
            names.append(record.value())
    return names

# define a function to find a node by it's name
def find_node_by_name(tx, name) -> list:
    result = tx.run(
        "MATCH (n) WHERE n.property_name = \"" + str(name) + "\" RETURN ID(n)"
    )
    nodes = []
    for record in result:
        nodes.append(record.value())
    return nodes

# define a function to generate ID for node randomly
def generate_node_id(currentKnowledgeSpaceName: str, currentCollaborationName: str) -> str:
    id1 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 8))
    id2 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id3 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id4 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id5 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 12))
    nodeId = 'node_' + id1 + '-' + id2 + '-' + id3 + '-' + id4 + '-' + id5 + '_c__' + currentCollaborationName + '_k__' + currentKnowledgeSpaceName
    return nodeId

# define a function to set a label to a node
def set_label_node(tx, node: int, label: str):
    tx.run(
        'MATCH (n) WHERE ID(n) = ' + str(node) +
        ' SET n:`' + label + '`'
    )

# define a function to set a property to a node
def set_property_node(tx, node: int, property_name: str, propertyValue: str):
    tx.run(
        'MATCH (n) WHERE ID(n) = ' + str(node) +
        ' SET n.' + property_name + ' = \"' + propertyValue + '\"'
    )

# define a function to get the labels of a node
def get_labels_node(tx, node: int) -> list[str]:
    labels = []
    result = tx.run(
        'MATCH (n) WHERE ID(n) = ' + str(node) +
        ' RETURN LABELS(n)'
    )
    for record in result:
        labels = record.value()
        return labels

# define a function to get the names of the properties of a node
def get_properties_names_node(tx, node: int) -> list[str]:
    keys = []
    result= tx.run(
        'MATCH (n) WHERE ID(n) = ' + str(node) +
        ' RETURN KEYS(n)'
    )
    for record in result:
        keys = record.value()
        break
    return keys

# define a function to get the properties of a node
def get_properties_node(tx, node: int) -> dict:
    keys = get_properties_names_node(tx, node)
    properties = {}
    for key in keys:
        result = tx.run(
            'MATCH (n) WHERE ID(n) = ' + str(node) +
            ' RETURN n.`' + key + '`'
        )
        for record in result:
            properties[key] = reformalize_property(record.value())
            break
    replace_list(properties)
    return properties

# define a function to get a specific property of a node based on the name of the property
def get_property_node(tx, node: int, name: str):
    keys = get_properties_names_node(tx, node)
    if name not in keys:
        return 'The property doesn\'t exist!'
    else:
        result = tx.run(
            'MATCH (n) WHERE ID(n) = ' + str(node) +
            ' RETURN n.`' + name + '`'
        )
        for record in result:
            value = reformalize_property(record.value())
            break
        if type(value) is dict:
            replace_list(value)
        return value

# define a function to create a node and return its identity
def create_node(tx, labels: list[str], properties: dict) -> int:
    result = tx.run(
        'CREATE (n:instance) RETURN ID(n)'
    )
    for record in result:
        node = int(record.value())
        break
    for label in labels:
        set_label_node(tx, node, label)
    for key, value in properties.items():
        set_property_node(tx, node, key, value)
    return node

# define a function to encode the property 'propertyLabels'
def encode_property_labels(propertyLabels) -> str:
    '''
    propertyLabels should be a list of labels
    '''
    temp = []
    for label in propertyLabels:
        temp.append([{'name': 'label', 'value': label}])
    return json.dumps(temp).replace('\"', '\'')

# define a function to encode the property 'geolocation'
def encode_geolocation(nodeType, point = None) -> str:
    '''
    point should be a list of latitude, longitude, altitude
    '''
    temp = {'itemView': [{}]}
    if (nodeType != 'Territory') and (point != None):
        temp['itemView'][0]['point'] = {
            'latitude': point[0],
            'longitude': point[1],
            'altitude': point[2]
        }
    if nodeType == 'Territory':
        temp['itemView'][0]['area'] = {
            'strokeColor': '#D8BFD8',
            'strokeWidth': 3.0,
            'strokeOpacity': 0.4,
            'fillColor': '#D8BFD8',
            'fillOpacity': 0.4
        }
    return json.dumps(temp).replace('\"', '\'')

# define a function to generate relatively position in the panel
def position_generator():
    a, b, c, d = 0, 0, 0, 0
    panel = (yield [0.0, 0.0])
    while True:
        if panel == 'Objectives':
            x = (a % 10 + 0.5) * 120.0
            y = (a // 10 + 0.5) * 120.0
            a += 1
            panel = (yield [x, y])
        elif panel == 'Collaborative process':
            x = (b % 10 + 0.5) * 120.0
            y = (b // 10 + 0.5) * 120.0
            b += 1
            panel = (yield [x, y])
        elif panel == 'Context':
            x = (c % 10 + 0.5) * 120.0
            y = (c // 10 + 0.5) * 120.0
            c += 1
            panel = (yield [x, y])
        elif panel == 'Context and partners':
            x = (d % 10 + 0.5) * 120.0
            y = (d // 10 + 0.5) * 120.0
            d += 1
            panel = (yield [x, y])

# Instantiate the position generator
POSITION_GEN = position_generator()
next(POSITION_GEN)

# define a function to generate itemView
def generate_item_view(panel) -> list:
    position = POSITION_GEN.send(panel)
    temp = [{
        'viewId': generate_view_id(),
        'view': {
            'defaultWidth' : 48.0,
            'defaultHeight' : 48.0
        },
        'position': {
            'x': position[0],
            'y': position[1]
        },
        'dimension': {
            'width' : 48.0,
            'height' : 48.0
        }
    }]
    return temp

# define a function to encode the property 'modeling'
def encode_modeling(nodeType, propertyType = None) -> str:
    if nodeType == 'Objective':
        temp = {
            'package': [{
                'itemView': generate_item_view('Objectives')
            }]
        }
        temp['package'][0]['name'] = 'Objectives'
        temp['package'][0]['itemView'][0].pop('view')
    if nodeType == 'Potential':
        temp = {
            'package': [{
                'itemView': generate_item_view('Objectives')
            }]
        }
        temp['package'][0]['name'] = 'Objectives'
        if propertyType == 'Danger':
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['potential danger']
        elif propertyType == 'Favorable Circumstance':
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['potential favorable circumstance']
        else:
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['potential neutral']
    if nodeType == 'Potentiality':
        temp = {
            'package': [{
                'itemView': generate_item_view('Objectives')
            }]
        }
        temp['package'][0]['name'] = 'Objectives'
        temp['package'].append({'itemView': generate_item_view('Collaborative process')})
        temp['package'][1]['name'] = 'Collaborative process'
        if propertyType == 'Risk':
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['potentiality risk']
            temp['package'][1]['itemView'][0]['view']['url'] = ICON_PATH['potentiality risk']
        elif propertyType == 'Opportunity':
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['potentiality opportunity']
            temp['package'][1]['itemView'][0]['view']['url'] = ICON_PATH['potentiality opportunity']
        else:
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['potentiality neutral']
            temp['package'][1]['itemView'][0]['view']['url'] = ICON_PATH['potentiality neutral']
    if nodeType == 'Actuality':
        temp = {
            'package': [{
                'itemView': generate_item_view('Objectives')
            }]
        }
        temp['package'][0]['name'] = 'Objectives'
        if propertyType == 'Damage':
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['actuality damage']
        elif propertyType == 'Benefit':
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['actuality benefit']
        else:
            temp['package'][0]['itemView'][0]['view']['url'] = ICON_PATH['actuality neutral']
    if nodeType in ['Person', 'Good', 'Territory', 'Community', 'Environment_Component']:
        temp = {
            'package': [{
                'itemView': generate_item_view('Context and partners')
            }]
        }
        temp['package'][0]['name'] = 'Context and partners'
        temp['package'][0]['itemView'][0].pop('view')
    return json.dumps(temp).replace('\"', '\'')

# define a function to encode probability for potentiality
def encode_probability(probability) -> str:
    if type(probability) is list:
        temp = {'theoricValue': {'ranges': [{'min': min(probability), 'max': max(probability)}]}}
    else:
        temp = {'theoricValue': {'precise': probability}}
    return json.dumps(temp).replace('\"', '\'')

# define a function to create a node:objective
def create_objective(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    objectiveName: str,
    status: str,
    description = None,
    priority = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    status should be 'ACTIVE' or 'FREEZE'
    priority should be a integer
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Objective'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Objective',
        'extends': '[{http://fr.emac.gind/core-model}Semantic_Concept]',
        'status': '[' + status + ']',
        'property_name': objectiveName,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if priority != None:
        properties['property_priority'] = str(priority)
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the latitude, longitude and altitude of the objective
    if point != None:
        properties['geolocation'] = encode_geolocation('Objective', point)
    # randomly setting position for view
    properties['modeling'] = encode_modeling('Objective')
    obj = create_node(tx, labels, properties)
    return obj

# define a function to create a node:potential
def create_potential(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    potentialName: str,
    status: str,
    potentialType = 'Neutral',
    description = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    potentialType should be 'Neutral' or 'Danger' or 'Favorable Circumstance'
    status should be 'ACTIVE' or 'FREEZE'
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Potential'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Potential',
        'extends': '[{http://fr.emac.gind/core-model}Semantic_Concept]',
        'status': '[' + status + ']',
        'property_name': potentialName,
        'property_type': potentialType,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the latitude, longitude and altitude of the potential
    if point != None:
        properties['geolocation'] = encode_geolocation('Potential', point)
    # setting correct icon base on the type of potential
    properties['modeling'] = encode_modeling('Potential', potentialType)
    potential = create_node(tx, labels, properties)
    return potential

# define a function to create a node:potentiality
def create_potentiality(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    potentialityName: str,
    status: str,
    potentialityType = 'Neutral',
    potentialityNature = 'Intrinsinc',
    probability = 0.01,
    description = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    potentialityType should be 'Neutral' or 'Risk' or 'Opportunity'
    potentialityNature should be 'Intrinsinc' or 'Emerging' or 'Implementation'
    status should be 'ACTIVE' or 'FREEZE'
    probability could be a number, or a list of two numbers (indicate a range)
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Potentiality'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Potentiality',
        'extends': '[{http://fr.emac.gind/core-model}Semantic_Concept]',
        'status': '[' + status + ']',
        'property_name': potentialityName,
        'property_type': potentialityType,
        'property_nature': potentialityNature,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the probability
    properties['property_probability'] = encode_probability(probability)
    # setting the latitude, longitude and altitude of the potentiality
    if point != None:
        properties['geolocation'] = encode_geolocation('Potentiality', point)
    # setting the correct icon based on the type of potentiality
    properties['modeling'] = encode_modeling('Potentiality', potentialityType)
    potentiality = create_node(tx, labels, properties)
    return potentiality

# define a function to create actuality
def create_actuality(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    actualityName: str,
    status: str,
    actualityType = 'Neutral',
    description = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    actualityType should be 'Neutral' or 'Damage' or 'Benefit'
    status should be 'ACTIVE' or 'FREEZE'
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Actuality'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Actuality',
        'extends': '[{http://fr.emac.gind/core-model}Semantic_Concept]',
        'status': '[' + status + ']',
        'property_name': actualityName,
        'property_type': actualityType,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the latitude, longitude and altitude of the actuality
    if point != None:
        properties['geolocation'] = encode_geolocation('Actuality', point)
    # setting the correct icon based on the type of actuality
    properties['modeling'] = encode_modeling('Actuality', actualityType)
    actuality = create_node(tx, labels, properties)
    return actuality

# define a function to create person
def create_person(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    personName: str,
    status: str,
    description = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    status should be 'ACTIVE' or 'FREEZE'
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Asset',
        '{http://fr.emac.gind/collaborative-model}Person',
        '{http://fr.emac.gind/collaborative-model}Resource'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Person',
        'extends': json.dumps([
            '{http://fr.emac.gind/core-model}Semantic_Concept',
            '{http://fr.emac.gind/collaborative-model}Asset',
            '{http://fr.emac.gind/collaborative-model}Resource'
        ]).replace('\"', ''),
        'status': '[' + status + ']',
        'property_name': personName,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the latitude, longitude and altitude of the person
    if point != None:
        properties['geolocation'] = encode_geolocation('Person', point)
    # randomly setting position for view
    properties['modeling'] = encode_modeling('Person')
    person = create_node(tx, labels, properties)
    return person

# define a function to create good
def create_good(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    goodName: str,
    status: str,
    description = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    status should be 'ACTIVE' or 'FREEZE'
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Asset',
        '{http://fr.emac.gind/collaborative-model}Good',
        '{http://fr.emac.gind/collaborative-model}Resource'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Good',
        'extends': json.dumps([
            '{http://fr.emac.gind/core-model}Semantic_Concept',
            '{http://fr.emac.gind/collaborative-model}Asset',
            '{http://fr.emac.gind/collaborative-model}Resource'
        ]).replace('\"', ''),
        'status': '[' + status + ']',
        'property_name': goodName,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the latitude, longitude and altitude of the good
    if point != None:
        properties['geolocation'] = encode_geolocation('Good', point)
    # randomly setting position for view
    properties['modeling'] = encode_modeling('Good')
    good = create_node(tx, labels, properties)
    return good

# define a function to create territory
def create_territory(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    territoryName: str,
    status: str,
    description = None,
    propertyLabels = None
) -> int:
    '''
    status should be 'ACTIVE' or 'FREEZE'
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Territory'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Territory',
        'extends': '[{http://fr.emac.gind/core-model}Semantic_Concept]',
        'status': '[' + status + ']',
        'property_name': territoryName,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # settubg the geolocation
    #properties['geolocation'] = encode_geolocation('Territory')
    # randomly setting position for view
    properties['modeling'] = encode_modeling('Territory')
    territory = create_node(tx, labels, properties)
    return territory

# define a function to create community
def create_community(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    communityName: str,
    status: str,
    description = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    status should be 'ACTIVE' or 'FREEZE'
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Asset',
        '{http://fr.emac.gind/collaborative-model}Community',
        '{http://fr.emac.gind/collaborative-model}Resource'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Community',
        'extends': json.dumps([
            '{http://fr.emac.gind/core-model}Semantic_Concept',
            '{http://fr.emac.gind/collaborative-model}Asset',
            '{http://fr.emac.gind/collaborative-model}Resource'
        ]).replace('\"', ''),
        'status': '[' + status + ']',
        'property_name': communityName,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the latitude, longitude and altitude of the community
    if point != None:
        properties['geolocation'] = encode_geolocation('Community', point)
    # randomly setting position for view
    properties['modeling'] = encode_modeling('Community')
    person = create_node(tx, labels, properties)
    return person

# define a function to create environment component
def create_environment_component(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    environmentComponentName: str,
    status: str,
    description = None,
    propertyLabels = None,
    point = None
) -> int:
    '''
    status should be 'ACTIVE' or 'FREEZE'
    propertyLabels should be a list of labels
    point should be a list of latitude, longitude, altitude
    '''
    labels = [
        status,
        currentKnowledgeSpaceName,
        currentCollaborationName,
        '{http://fr.emac.gind/core-model}Semantic_Concept',
        '{http://fr.emac.gind/collaborative-model}Asset',
        '{http://fr.emac.gind/collaborative-model}Environment_Component'
    ]
    properties = {
        'type': '{http://fr.emac.gind/collaborative-model}Environment_Component',
        'extends': json.dumps([
            '{http://fr.emac.gind/core-model}Semantic_Concept',
            '{http://fr.emac.gind/collaborative-model}Asset'
        ]).replace('\"', ''),
        'status': '[' + status + ']',
        'property_name': environmentComponentName,
        'modelNodeId': generate_node_id(currentKnowledgeSpaceName, currentCollaborationName)
    }
    if description != None:
        properties['property_description'] = description
    if propertyLabels != None:
        properties['property_labels'] = encode_property_labels(propertyLabels)
    # setting the latitude, longitude and altitude of the good
    if point != None:
        properties['geolocation'] = encode_geolocation('Environment_Component', point)
    # randomly setting position for view
    properties['modeling'] = encode_modeling('Environment_Component')
    environmentComponent = create_node(tx, labels, properties)
    return environmentComponent

# define a function to delete a node based on given id
def delete_node(tx, id: int):
    tx.run(
        'MATCH (n) WHERE ID(n)=' + str(id) + ' DELETE n'
    )

# Functions for edge
# define a function to generate ID for edge randomly
def generate_edge_id(currentKnowledgeSpaceName: str, currentCollaborationName: str) -> str:
    id1 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 8))
    id2 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id3 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id4 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 4))
    id5 = ''.join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 12))
    edgeId = 'edge_' + id1 + '-' + id2 + '-' + id3 + '-' + id4 + '-' + id5 + '_c__' + currentCollaborationName + '_k__' + currentKnowledgeSpaceName
    return edgeId

# define a function to get the information of an edge
def get_info_edge(tx, edge: int) -> dict:
    info = {}
    result = tx.run(
        'MATCH ()-[r]->() WHERE ID(r) = ' + str(edge) +
        ' RETURN r'
    )
    for record in result:
        temp = record.value()
        break
    info['identity'] = temp.id
    info['start'] = temp.nodes[0].id
    info['end'] = temp.nodes[1].id
    info['type'] = temp.type
    return info

# define a function to get the names of the properties of an edge
def get_properties_names_edge(tx, edge: int) -> list[str]:
    keys = []
    result= tx.run(
        'MATCH ()-[r]->() WHERE ID(r) = ' + str(edge) +
        ' RETURN KEYS(r)'
    )
    for record in result:
        keys = record.value()
        break
    return keys

# define a function to get the properties of an edge
def get_properties_edge(tx, edge: int) -> dict:
    properties = {}
    result = tx.run(
        'MATCH ()-[r]->() WHERE ID(r) = ' + str(edge) +
        ' RETURN r'
    )
    for record in result:
        temp = record.value()
        break
    keys = temp.keys()
    for key in keys:
        properties[key] = reformalize_property(temp.get(key))
    return properties

# define a function to get a specific property of an edge based on the name of the property
def get_property_edge(tx, edge: int, name: str):
    keys = get_properties_names_edge(tx, edge)
    if name not in keys:
        return 'The property doesn\'t exist!'
    else:
        result = tx.run(
            'MATCH ()-[r]-() WHERE ID(r) = ' + str(edge) +
            ' RETURN r.`' + name + '`'
        )
        for record in result:
            value = reformalize_property(record.value())
            break
        if type(value) is dict:
            replace_list(value)
        return value

# define a function to set a property to an edge
def set_property_edge(tx, edge: int, property_name: str, propertyValue):
    tx.run(
        'MATCH ()-[r]->(b) WHERE ID(r) = ' + str(edge) +
        ' SET r.' + property_name + ' = \"' + str(propertyValue) + '\"'
    )

# define a function to create an edge between two nodes
def create_edge(
    tx,
    currentKnowledgeSpaceName: str,
    currentCollaborationName: str,
    start: int,
    end: int,
    edgeType: str,
    properties = None
) -> int:
    result = tx.run(
        'MATCH (a), (b) WHERE id(a) = ' + str(start) + ' and id(b) = ' + str(end) +
        ' CREATE (a)-[r:`' + EDGE_TYPE[edgeType] + '`]->(b) RETURN ID(r)'
    )
    for record in result:
        edge = int(record.value())
        break
    edgeId = generate_edge_id(currentKnowledgeSpaceName, currentCollaborationName)
    set_property_edge(tx, edge, 'modelEdgeId', edgeId)
    set_property_edge(tx, edge, 'property_name', edgeType)
    if properties:
        for key, value in properties.items():
            set_property_edge(tx, edge, key, value)
    brokenEdge = {
        'edge': {
            'id': edgeId[:41],
            'type': EDGE_TYPE[edgeType],
            'source': get_property_node(tx, start, 'modelNodeId')[:41],
            'property': [{
                'name': 'name',
                'value': edgeType
            }]
        },
        'sourceId': get_property_node(tx, start, 'modelNodeId')[:41],
        'targetId': get_property_node(tx, end, 'modelNodeId')[:41]
    }
    if properties:
        for key, value in properties.items():
            brokenEdge['edge']['property'].append({
                'name': key[9:],
                'value': value
            })
    brokenEdges = get_property_node(tx, start, 'brokenEdges')
    if brokenEdges == 'The property doesn\'t exist!':
        brokenEdges = {'brokenEdge': []}
    else:
        if not 'brokenEdge' in brokenEdges.keys():
            brokenEdges['brokenEdge'] = []
    brokenEdges['brokenEdge'].append(brokenEdge)
    set_property_node(tx, start, 'brokenEdges', json.dumps(brokenEdges).replace('\"', '\''))
    return edge

# define a function to delete an edge based on given id
def delete_edge(tx, id: int):
    result = tx.run(
        'MATCH (a)-[r]->(b) WHERE ID(r)=' + str(id) + ' RETURN ID(a)'
    )
    for record in result:
        start = int(record.value())
        break
    edgeId = get_property_edge(tx, id, 'modelEdgeId')
    brokenEdges = get_property_node(tx, start, 'brokenEdges')
    if brokenEdges:
        if 'brokenEdge' in brokenEdges.keys():
            for edge in brokenEdges['brokenEdge']:
                if edge['edge']['id'] == edgeId[:41]:
                    brokenEdges['brokenEdge'].remove(edge)
                    set_property_node(tx, start, 'brokenEdges', json.dumps(brokenEdges).replace('\"', '\''))
    tx.run(
        'MATCH (a)-[r]->(b) WHERE ID(r)=' + str(id) + ' DELETE r'
    )

# Functions for concepts
# define a function to formalize the JSON to be posted to CEA
def JSON_to_CEA(tx, nodes):
    '''
    nodes should be a list of the ID of nodes
    '''
    postJSON = {
        "collaborationName": tx.read_transaction(get_current_collaboration_name).replace('_', ' '),
        "knowledgeSpaceName": tx.read_transaction(get_current_knowledge_space_name).replace('_', ' '),
        "rio_model": {
            "edge": [],
            "node": [],
        }
    }
    for node in nodes:
        postJSON['rio_model']['node'].append(get_properties_node(tx, node))
    return postJSON
    
# define a function to instantiate a potential
def instantiate_potential(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose = False):
    nodesNames = get_all_nodes_names(tx)
    if concept['potentialName'] in nodesNames:
        existingNodes = find_node_by_name(tx, concept['potentialName'])
        for node in existingNodes:
            existingLabels = get_property_node(tx, node, 'property_labels')
            propertyLabels = []
            for label in existingLabels:
                propertyLabels.append(label[0]['value'])
            if not concept['propertyLabels'][-1] in propertyLabels:
                propertyLabels.append(concept['propertyLabels'][-1])
            set_property_node(tx, node, 'property_labels', encode_property_labels(propertyLabels))
        return existingNodes
    else:
        potential = create_potential(
            tx,
            currentKnowledgeSpaceName = currentKnowledgeSpaceName,
            currentCollaborationName = currentCollaborationName,
            potentialName = concept['potentialName'],
            status = concept['status'],
            potentialType = concept['potentialType'],
            description = concept['description'],
            propertyLabels = concept['propertyLabels']
        )
        postJOSN = json.dumps(JSON_to_CEA(tx, [potential]))
        reqPost = requests.post(URL, data = postJOSN, headers = HEADERS)
        if verbose:
            print(reqPost.url)
            print(reqPost.text)
            print(reqPost.status_code)
            print(postJOSN)
            print()
        return potential

# define a function to instantiate a actuality
def instantiate_actuality(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose = False):
    nodesNames = get_all_nodes_names(tx)
    if concept['actualityName'] in nodesNames:
        existingNodes = find_node_by_name(tx, concept['actualityName'])
        for node in existingNodes:
            existingLabels = get_property_node(tx, node, 'property_labels')
            propertyLabels = []
            for label in existingLabels:
                propertyLabels.append(label[0]['value'])
            if not concept['propertyLabels'][-1] in propertyLabels:
                propertyLabels.append(concept['propertyLabels'][-1])
            set_property_node(tx, node, 'property_labels', encode_property_labels(propertyLabels))
        return existingNodes
    else:
        actuality = create_actuality(
            tx,
            currentKnowledgeSpaceName = currentKnowledgeSpaceName,
            currentCollaborationName = currentCollaborationName,
            actualityName = concept['actualityName'],
            status = concept['status'],
            actualityType = concept['actualityType'],
            description = concept['description'],
            propertyLabels = concept['propertyLabels']
        )
        postJOSN = json.dumps(JSON_to_CEA(tx, [actuality]))
        reqPost = requests.post(URL, data = postJOSN, headers = HEADERS)
        if verbose:
            print(reqPost.url)
            print(reqPost.text)
            print(reqPost.status_code)
            print(postJOSN)
            print()
        return actuality

# define a function to instantiate a person
def instantiate_person(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose = False):
    nodesNames = get_all_nodes_names(tx)
    if concept['personName'] in nodesNames:
        existingNodes = find_node_by_name(tx, concept['personName'])
        for node in existingNodes:
            existingLabels = get_property_node(tx, node, 'property_labels')
            propertyLabels = []
            for label in existingLabels:
                propertyLabels.append(label[0]['value'])
            if not concept['propertyLabels'][-1] in propertyLabels:
                propertyLabels.append(concept['propertyLabels'][-1])
            set_property_node(tx, node, 'property_labels', encode_property_labels(propertyLabels))
        return existingNodes
    else:
        person = create_person(
            tx,
            currentKnowledgeSpaceName = currentKnowledgeSpaceName,
            currentCollaborationName = currentCollaborationName,
            personName = concept['personName'],
            status = concept['status'],
            description = concept['description'],
            propertyLabels = concept['propertyLabels']
        )
        postJOSN = json.dumps(JSON_to_CEA(tx, [person]))
        reqPost = requests.post(URL, data = postJOSN, headers = HEADERS)
        if verbose:
            print(reqPost.url)
            print(reqPost.text)
            print(reqPost.status_code)
            print(postJOSN)
            print()
        return person

# define a function to instantiate a good
def instantiate_good(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose = False):
    nodesNames = get_all_nodes_names(tx)
    if concept['goodName'] in nodesNames:
        existingNodes = find_node_by_name(tx, concept['goodName'])
        for node in existingNodes:
            existingLabels = get_property_node(tx, node, 'property_labels')
            propertyLabels = []
            for label in existingLabels:
                propertyLabels.append(label[0]['value'])
            if not concept['propertyLabels'][-1] in propertyLabels:
                propertyLabels.append(concept['propertyLabels'][-1])
            set_property_node(tx, node, 'property_labels', encode_property_labels(propertyLabels))
        return existingNodes
    else:
        good = create_good(
            tx,
            currentKnowledgeSpaceName = currentKnowledgeSpaceName,
            currentCollaborationName = currentCollaborationName,
            goodName = concept['goodName'],
            status = concept['status'],
            description = concept['description'],
            propertyLabels = concept['propertyLabels']
        )
        postJOSN = json.dumps(JSON_to_CEA(tx, [good]))
        reqPost = requests.post(URL, data = postJOSN, headers = HEADERS)
        if verbose:
            print(reqPost.url)
            print(reqPost.text)
            print(reqPost.status_code)
            print(postJOSN)
            print()
        return good

# define a function to instantiate a concept
def instantiate_concept(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose = False):
    if concept['conceptType'] == 'potential':
        return instantiate_potential(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose)
    elif concept['conceptType'] == 'actuality':
        return instantiate_actuality(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose)
    elif concept['conceptType'] == 'person':
        return instantiate_person(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose)
    elif concept['conceptType'] == 'good':
        return instantiate_good(tx, concept, currentKnowledgeSpaceName, currentCollaborationName, verbose)
    else:
        return None